# Generated by Django 5.0.3 on 2024-10-07 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=255, unique=True)),
                ('face_encoding', models.BinaryField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('department', models.CharField(max_length=255)),
                ('enrollment_date', models.DateField()),
                ('enrollment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_email', models.EmailField(max_length=255)),
                ('parent_phone', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teacher_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('qualifications', models.TextField()),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('department', models.CharField(max_length=255)),
                ('professional_development', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.URLField()),
                ('report_reason', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.URLField()),
                ('status', models.CharField(choices=[('Identified', 'Identified'), ('Unidentified', 'Unidentified')], max_length=15)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=10)),
                ('attendance_time', models.DateTimeField()),
                ('reason_for_absence', models.CharField(blank=True, max_length=255, null=True)),
                ('camera_id', models.IntegerField(blank=True, null=True)),
                ('system_status', models.CharField(choices=[('Operational', 'Operational'), ('Error', 'Error')], max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
