# Generated by Django 5.0.3 on 2024-10-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_semester_rename_course_name_timetable_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
